"""empty message

Revision ID: 167e3af42a51
Revises: a280c68ac54b
Create Date: 2020-04-18 17:03:18.815460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167e3af42a51'
down_revision = 'a280c68ac54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.Enum('正常', '异常'), server_default='正常', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
