"""empty message

Revision ID: 326286468f78
Revises: bfbd40b8d546
Create Date: 2020-04-18 11:04:37.370491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '326286468f78'
down_revision = 'bfbd40b8d546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('gaode_latitude', sa.Float(precision='15,8'), nullable=True))
    op.add_column('equipment', sa.Column('gaode_longitude', sa.Float(), nullable=True))
    op.drop_column('equipment', 'ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('ip', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('equipment', 'gaode_longitude')
    op.drop_column('equipment', 'gaode_latitude')
    # ### end Alembic commands ###
