"""empty message

Revision ID: 444b48987eb0
Revises: 9907b6d67d7d
Create Date: 2020-05-06 19:44:35.325318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444b48987eb0'
down_revision = '9907b6d67d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture', sa.LargeBinary(length=4294967295), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture')
    # ### end Alembic commands ###
