"""empty message

Revision ID: 590081006b40
Revises: 167e3af42a51
Create Date: 2020-04-18 17:05:34.767774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590081006b40'
down_revision = '167e3af42a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('temperature', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'temperature')
    # ### end Alembic commands ###
