"""empty message

Revision ID: 681412ff640a
Revises: 93a9f4a60f1d
Create Date: 2020-04-23 20:28:42.135211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '681412ff640a'
down_revision = '93a9f4a60f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', mysql.ENUM('正常', '异常'), server_default=sa.text("'正常'"), nullable=True))
    # ### end Alembic commands ###
