"""empty message

Revision ID: a280c68ac54b
Revises: 23a7265f2260
Create Date: 2020-04-18 17:00:37.301832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a280c68ac54b'
down_revision = '23a7265f2260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm_record', 'if_sure')
    op.drop_column('alarm_record', 'class_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_record', sa.Column('class_', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('alarm_record', sa.Column('if_sure', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
