"""empty message

Revision ID: abe75009380c
Revises: 
Create Date: 2020-04-14 19:39:05.947576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe75009380c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('if_add_student', sa.BOOLEAN(), nullable=True),
    sa.Column('if_look_other', sa.BOOLEAN(), nullable=True),
    sa.Column('if_sure', sa.BOOLEAN(), nullable=True),
    sa.Column('if_drop_user', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('college',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dormitory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('正常', '故障'), server_default='正常', nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_people.id'], ),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('正常', '异常'), server_default='正常', nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alarm_time', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('telephone', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=10), nullable=True),
    sa.Column('dormitory_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.ForeignKeyConstraint(['dormitory_id'], ['dormitory.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarm_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_', sa.String(length=100), nullable=False),
    sa.Column('alarm_time', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.String(length=100), nullable=True),
    sa.Column('if_sure', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('正常', '异常'), server_default='正常', nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_log')
    op.drop_table('alarm_record')
    op.drop_table('user')
    op.drop_table('equipment_record')
    op.drop_table('equipment_log')
    op.drop_table('class')
    op.drop_table('equipment')
    op.drop_table('dormitory')
    op.drop_table('college')
    op.drop_table('admin_people')
    op.drop_table('role')
    # ### end Alembic commands ###
