"""empty message

Revision ID: aeca8c9a26ac
Revises: fc1653a25d4b
Create Date: 2020-04-18 11:56:09.472986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aeca8c9a26ac'
down_revision = 'fc1653a25d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'gaode_latitude')
    op.drop_column('equipment', 'gaode_longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('gaode_longitude', mysql.FLOAT(), nullable=True))
    op.add_column('equipment', sa.Column('gaode_latitude', mysql.FLOAT(precision=15, scale=8), nullable=True))
    # ### end Alembic commands ###
