"""empty message

Revision ID: bfbd40b8d546
Revises: abe75009380c
Create Date: 2020-04-15 22:52:14.248380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfbd40b8d546'
down_revision = 'abe75009380c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'location')
    # ### end Alembic commands ###
